# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI's/confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlQuery
from databaseConn import createConnection
from Message import Ui_MessageForm
from signalConnection import SignalConnector


class Ui_ConfirmDialog(object):
    def removeEntry(self, id : int) -> None:
        message_code = "Error"
        message = "An Error Occured"
        try:
            db = createConnection()
            db.open()
            query = QSqlQuery()
            checker = QSqlQuery()

            checker_statement = "SELECT COUNT(*) FROM products WHERE id = :id"
            checker.prepare(checker_statement)
            checker.bindValue(":id", id)
            checker_status = checker.exec_()

            if checker_status:
                checker.next()
                count = checker.value(0)
                if count == 1:
                    statement = "DELETE FROM products WHERE id = :id"
                    query.prepare(statement)
                    query.bindValue(":id", id)
                    status = query.exec_()
                    
                    if status:
                        message = "Deleted Successfully!"
                        message_code = "Success"
                        self.signal.clickedOk.emit()
                else:
                    message = "Data Don't Exist"
            else:
                message = "Data Don't Exist"
        except Exception as e:
            message = str(e)[:13] + "..."

        db.close()
        self.messageFedback(message, message_code)
    
    def messageFedback(self, msg : str, code : str) -> None:
        self.erorr = QtWidgets.QDialog()
        erorr_modal = Ui_MessageForm(msg, code)
        erorr_modal.setupUi(self.erorr)
        self.ConfirmDialog.close()
        self.erorr.exec_()
    
    def setupUi(self, ConfirmDialog):
        ConfirmDialog.setObjectName("ConfirmDialog")
        ConfirmDialog.setFixedSize(274, 120)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConfirmDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ConfirmWidget = QtWidgets.QWidget(ConfirmDialog)
        self.ConfirmWidget.setObjectName("ConfirmWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ConfirmWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConfirmLabel = QtWidgets.QLabel(self.ConfirmWidget)
        self.ConfirmLabel.setObjectName("ConfirmLabel")
        self.verticalLayout.addWidget(self.ConfirmLabel, 0, QtCore.Qt.AlignHCenter)
        self.ConfirmSeparator = QtWidgets.QFrame(self.ConfirmWidget)
        self.ConfirmSeparator.setFrameShape(QtWidgets.QFrame.HLine)
        self.ConfirmSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ConfirmSeparator.setObjectName("ConfirmSeparator")
        self.verticalLayout.addWidget(self.ConfirmSeparator)
        self.ConfirmButtonWidget = QtWidgets.QWidget(self.ConfirmWidget)
        self.ConfirmButtonWidget.setObjectName("ConfirmButtonWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ConfirmButtonWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfirmNoButton = QtWidgets.QPushButton(self.ConfirmButtonWidget)
        self.ConfirmNoButton.setObjectName("ConfirmNoButton")
        self.horizontalLayout.addWidget(self.ConfirmNoButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ConfirmYesButton = QtWidgets.QPushButton(self.ConfirmButtonWidget)
        self.ConfirmYesButton.setObjectName("ConfirmYesButton")
        self.horizontalLayout.addWidget(self.ConfirmYesButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.ConfirmButtonWidget)
        self.verticalLayout_2.addWidget(self.ConfirmWidget)

        self.retranslateUi(ConfirmDialog)
        self.ConfirmNoButton.clicked.connect(ConfirmDialog.close)
        # self.ConfirmYesButton.clicked.connect(self.removeEntry)
        QtCore.QMetaObject.connectSlotsByName(ConfirmDialog)
        self.ConfirmDialog = ConfirmDialog

        self.signal = SignalConnector()


    def retranslateUi(self, ConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDialog.setWindowTitle(_translate("ConfirmDialog", "Dialog"))
        self.ConfirmLabel.setText(_translate("ConfirmDialog", "Are you sure you want to remove?"))
        self.ConfirmNoButton.setText(_translate("ConfirmDialog", "No"))
        self.ConfirmYesButton.setText(_translate("ConfirmDialog", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmDialog = QtWidgets.QDialog()
    ui = Ui_ConfirmDialog(1)
    ui.setupUi(ConfirmDialog)
    ConfirmDialog.show()
    sys.exit(app.exec_())
