# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI's/Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Message import Ui_MessageForm
import signup
from SessionManager import Session

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Upper = QtWidgets.QWidget(self.centralwidget)
        self.Upper.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Upper.setObjectName("Upper")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Upper)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LogSignWidget = QtWidgets.QWidget(self.Upper)
        self.LogSignWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.LogSignWidget.setObjectName("LogSignWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LogSignWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.SignUpButton = QtWidgets.QPushButton(self.LogSignWidget)
        self.SignUpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUpButton.setStyleSheet("QPushButton {\n"
        "    background-color: rgba(0,0,0,0);\n"
        "    border:rgba(0,0,0,0);\n"
        "}\n"
        "QPushButton:hover {\n"
        "    color:blue;\n"
        "}\n"
        "")
        self.SignUpButton.setObjectName("SignUpButton")
        self.horizontalLayout_2.addWidget(self.SignUpButton)
        self.line = QtWidgets.QFrame(self.LogSignWidget)
        self.line.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.LogInButton = QtWidgets.QPushButton(self.LogSignWidget)
        self.LogInButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogInButton.setStyleSheet("QPushButton {\n"
        "    background-color: rgba(0,0,0,0);\n"
        "    border:rgba(0,0,0,0);\n"
        "}\n"
        "QPushButton:hover {\n"
        "    color:blue;\n"
        "}")
        self.LogInButton.setObjectName("LogInButton")
        self.horizontalLayout_2.addWidget(self.LogInButton)
        self.horizontalLayout_3.addWidget(self.LogSignWidget)
        self.LogOutButton = QtWidgets.QPushButton(self.LogSignWidget)
        self.LogOutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogOutButton.setStyleSheet("QPushButton {\n"
            "    background-color: rgba(0,0,0,0);\n"
            "    border:rgba(0,0,0,0);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    color:red;\n"
            "}")
        self.LogOutButton.setObjectName("LogOutButton")
        self.horizontalLayout_2.addWidget(self.LogOutButton)
        self.verticalLayout.addWidget(self.Upper)
        self.TopBarWidget = QtWidgets.QWidget(self.centralwidget)
        self.TopBarWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TopBarWidget.setObjectName("TopBarWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.TopBarWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.MiddleDataHolder = QtWidgets.QWidget(self.TopBarWidget)
        self.MiddleDataHolder.setObjectName("MiddleDataHolder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MiddleDataHolder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.storeName = QtWidgets.QLabel(self.MiddleDataHolder)
        self.storeName.setObjectName("storeName")
        self.horizontalLayout.addWidget(self.storeName)
        self.SearchItem = QtWidgets.QLineEdit(self.MiddleDataHolder)
        self.SearchItem.setObjectName("SearchItem")
        self.horizontalLayout.addWidget(self.SearchItem)
        self.cartButton = QtWidgets.QPushButton(self.MiddleDataHolder)
        self.cartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cartButton.setStyleSheet("QPushButton {\n"
        "    background-color: rgba(0,0,0,0);\n"
        "    border:rgba(0,0,0,0);\n"
        "}\n"
        "QPushButton:hover {\n"
        "    color:blue;\n"
        "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\'s/../static/cart-shopping-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartButton.setIcon(icon)
        self.cartButton.setObjectName("cartButton")
        self.horizontalLayout.addWidget(self.cartButton)
        self.cartCount = QtWidgets.QLabel(self.MiddleDataHolder)
        self.cartCount.setMinimumSize(QtCore.QSize(20, 20))
        self.cartCount.setMaximumSize(QtCore.QSize(20, 20))
        self.cartCount.setStyleSheet("background-color:red;\n"
        "border:black solid 1px;\n"
        "border-radius: 10%;\n"
        "text-align:center;")
        self.cartCount.setObjectName("cartCount")
        self.horizontalLayout.addWidget(self.cartCount)
        self.horizontalLayout_4.addWidget(self.MiddleDataHolder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.TopBarWidget)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.Prods = QtWidgets.QWidget(self.centralwidget)
        self.Prods.setStyleSheet("background-color:white;")
        self.Prods.setObjectName("Prods")
        self.gridLayout = QtWidgets.QGridLayout(self.Prods)
        self.gridLayout.setObjectName("gridLayout")
        self.IndiProd = QtWidgets.QWidget(self.Prods)
        self.IndiProd.setMinimumSize(QtCore.QSize(250, 250))
        self.IndiProd.setMaximumSize(QtCore.QSize(200, 200))
        self.IndiProd.setStyleSheet("background-color:rgb(227, 227, 227);")
        self.IndiProd.setObjectName("IndiProd")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.IndiProd)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.IndiProd)
        self.widget_7.setMinimumSize(QtCore.QSize(238, 100))
        self.widget_7.setStyleSheet("border: black solid 1px;\n"
        "border-color: black;")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_2.addWidget(self.widget_7, 0, QtCore.Qt.AlignHCenter)
        self.line_3 = QtWidgets.QFrame(self.IndiProd)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.InfoHolder = QtWidgets.QWidget(self.IndiProd)
        self.InfoHolder.setMinimumSize(QtCore.QSize(220, 0))
        self.InfoHolder.setMaximumSize(QtCore.QSize(2324324, 25))
        self.InfoHolder.setObjectName("InfoHolder")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.InfoHolder)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ProdName = QtWidgets.QLabel(self.InfoHolder)
        self.ProdName.setObjectName("ProdName")
        self.horizontalLayout_6.addWidget(self.ProdName)
        self.ProdPrice = QtWidgets.QLabel(self.InfoHolder)
        self.ProdPrice.setObjectName("ProdPrice")
        self.horizontalLayout_6.addWidget(self.ProdPrice)
        self.verticalLayout_2.addWidget(self.InfoHolder)
        self.AddToCart = QtWidgets.QPushButton(self.IndiProd)
        self.AddToCart.setIcon(icon)
        self.AddToCart.setObjectName("AddToCart")
        self.verticalLayout_2.addWidget(self.AddToCart)
        self.gridLayout.addWidget(self.IndiProd, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Prods)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cartButton.clicked.connect(self.showCart)
        self.SignUpButton.clicked.connect(self.signUp)
        self.LogOutButton.clicked.connect(self.logOut)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.setButton()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.storeName.setText(_translate("MainWindow", "Someone\'s Online Store"))
        self.SearchItem.setPlaceholderText(_translate("MainWindow", "Search"))
        self.cartButton.setText(_translate("MainWindow", "Cart"))
        self.cartCount.setText(_translate("MainWindow", "  0"))
        self.ProdName.setText(_translate("MainWindow", "Name"))
        self.ProdPrice.setText(_translate("MainWindow", "Price"))
        self.AddToCart.setText(_translate("MainWindow", "Add To Cart"))
        self.SignUpButton.setText(_translate("MainWindow", "Sign Up"))
        self.LogInButton.setText(_translate("MainWindow", "Login"))
        self.LogOutButton.setText(_translate("MainWindow", "Log Out"))
        
    def showCart(self) -> None:
        self.underway = QtWidgets.QDialog()
        cart_ui = Ui_MessageForm("Available Soon!", "Underway")
        cart_ui.setupUi(self.underway)
        self.underway.exec_()
    
    def logOut(self) -> None:
        session = Session()
        session.clear()
        self.setButton()

    def signUp(self) -> None:
        self.sign_up_ui = QtWidgets.QDialog()
        sign_up = signup.Ui_Dialog()
        sign_up.setupUi(self.sign_up_ui)
        self.sign_up_ui.exec_()
        self.setButton()
    
    def setButton(self):
        session = Session()
        data = session.get()
        if data:
            self.LogInButton.hide()
            self.SignUpButton.hide()
            self.LogOutButton.show()
        else:
            self.LogInButton.show()
            self.SignUpButton.show()
            self.LogOutButton.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
