# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI's/SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Message import Ui_MessageForm
from werkzeug.security import check_password_hash, generate_password_hash
from PyQt5.QtSql import QSqlQuery
from databaseConn import createConnection
from SessionManager import Session


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(778, 677)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.signUpWidget = QtWidgets.QWidget(Dialog)
        self.signUpWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.signUpWidget.setObjectName("signUpWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.signUpWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.signUpWidget)
        self.line.setMinimumSize(QtCore.QSize(400, 0))
        self.line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line, 0, QtCore.Qt.AlignHCenter)
        self.usernamelabel = QtWidgets.QLabel(self.signUpWidget)
        self.usernamelabel.setMinimumSize(QtCore.QSize(200, 30))
        self.usernamelabel.setObjectName("usernamelabel")
        self.verticalLayout_2.addWidget(self.usernamelabel, 0, QtCore.Qt.AlignHCenter)
        self.usernameField = QtWidgets.QLineEdit(self.signUpWidget)
        self.usernameField.setMinimumSize(QtCore.QSize(200, 0))
        self.usernameField.setObjectName("usernameField")
        self.verticalLayout_2.addWidget(self.usernameField, 0, QtCore.Qt.AlignHCenter)
        self.password1Label = QtWidgets.QLabel(self.signUpWidget)
        self.password1Label.setMinimumSize(QtCore.QSize(200, 0))
        self.password1Label.setObjectName("password1Label")
        self.verticalLayout_2.addWidget(self.password1Label, 0, QtCore.Qt.AlignHCenter)
        self.password1 = QtWidgets.QLineEdit(self.signUpWidget)
        self.password1.setMinimumSize(QtCore.QSize(200, 0))
        self.password1.setObjectName("password1")
        self.password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_2.addWidget(self.password1, 0, QtCore.Qt.AlignHCenter)
        self.password2Label = QtWidgets.QLabel(self.signUpWidget)
        self.password2Label.setMinimumSize(QtCore.QSize(200, 0))
        self.password2Label.setObjectName("password2Label")
        self.verticalLayout_2.addWidget(self.password2Label, 0, QtCore.Qt.AlignHCenter)
        self.password2 = QtWidgets.QLineEdit(self.signUpWidget)
        self.password2.setMinimumSize(QtCore.QSize(200, 0))
        self.password2.setObjectName("password2")
        self.password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_2.addWidget(self.password2, 0, QtCore.Qt.AlignHCenter)
        self.MidWidget = QtWidgets.QWidget(self.signUpWidget)
        self.MidWidget.setObjectName("MidWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MidWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.SignUpbutton = QtWidgets.QPushButton(self.MidWidget)
        self.SignUpbutton.setObjectName("SignUpbutton")
        self.verticalLayout.addWidget(self.SignUpbutton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.MidWidget)
        self.verticalLayout_3.addWidget(self.signUpWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        self.SignUpbutton.clicked.connect(self.signUp)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Dialog = Dialog

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign Up To Someone\'s Online Store"))
        self.usernamelabel.setText(_translate("Dialog", "Username"))
        self.usernameField.setPlaceholderText(_translate("Dialog", "Username"))
        self.password1Label.setText(_translate("Dialog", "Password"))
        self.password1.setPlaceholderText(_translate("Dialog", "Password"))
        self.password2Label.setText(_translate("Dialog", "Re-Enter Password"))
        self.password2.setPlaceholderText(_translate("Dialog", "Password"))
        self.SignUpbutton.setText(_translate("Dialog", "Sign Up"))

    def signUp(self) -> None:
        username = self.usernameField.text()
        password = self.password1.text()
        password2 = self.password2.text()
        code = "Password"
        if not password or not password2 or not username:
            msg = "Fill all field!"
            self.signUpError(msg, code)
        else:            
            if password != password2:
                msg = "Password Don't Match"
                self.signUpError(msg, code)
            else:
                hashpass = generate_password_hash(password)
                type = 1
                db = createConnection()
                db.open()
                query = QSqlQuery()
                statement = "INSERT INTO users (username, password, type) VALUES (:username, :password, :type)"
                query.prepare(statement)
                query.bindValue(":username", username)
                query.bindValue(":password", hashpass)
                query.bindValue(":type", type)
                status = query.exec_()
                if status:
                    session = Session()
                    last_inserted_id = query.lastInsertId()
                    session.set(username, last_inserted_id, type)
                    self.Dialog.close()
                else:
                    msg = "Database Error!"
                    code = "Database"
                    self.signUpError(msg, code)
                db.close()

        
    

    def signUpError(self, msg : str, code : str) -> None:
        self.sign_up_error_ui = QtWidgets.QDialog()
        sign_up_error_ui = Ui_MessageForm(msg, code)
        sign_up_error_ui.setupUi(self.sign_up_error_ui)
        self.sign_up_error_ui.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
